export const PERMISSION = {
  ACTIONS: {
    CREATE: "CREATE",
    READ: "READ",
    UPDATE: "UPDATE",
    DELETE: "DELETE",
    WEIGH: "WEIGH",
    VERIFY_PLATE: "VERIFY_PLATE",
    VERIFY_PLATE_MANUAL: "VERIFY_PLATE_MANUAL",
    CHANGE_CUSTOMER: "CHANGE_CUSTOMER",
    REVISE_DO: "REVISE_DO",
    UNARCHIVE: "UNARCHIVE",
    READ_ARCHIVED: "READ_ARCHIVED",
    UPDATE_TALLY: "UPDATE_TALLY",
    UPDATE_KENEK: "UPDATE_KENEK",
  },
  RESOURCES: {
    DASHBOARD: "dashboard",
    USER: "user",
    ROLE: "role",
    PERMISSION: "permission",
    PRODUCT: "product",
    CUSTOMER: "customer",
    WAREHOUSE: "warehouse",
    DO: "delivery_order",
    ARMADA: "armada",
    DRIVER: "driver",
    PENGIRIMAN: "shipment",
    LAPORAN: "report",
    // Log resources
    USER_LOG: "user_log",
    PRODUCT_LOG: "product_log",
    CUSTOMER_LOG: "customer_log",
    WAREHOUSE_LOG: "warehouse_log",
    ARMADA_LOG: "armada_log",
    DO_LOG: "delivery_order_log",
    PENGIRIMAN_LOG: "shipment_log",
  },
};
