export const PERMISSION = {
  ACTIONS: {
    CREATE: "CREATE",
    READ: "READ",
    UPDATE: "UPDATE",
    DELETE: "DELETE",
    WEIGH: "WEIGH",
    VERIFY_PLATE: "VERIFY_PLATE",
    VERIFY_PLATE_MANUAL: "VERIFY_PLATE_MANUAL",
    CHANGE_CUSTOMER: "CHANGE_CUSTOMER",
    REVISE_DO: "REVISE_DO",
  },
  RESOURCES: {
    DASHBOARD: "dashboard",
    USER: "user",
    ROLE: "role",
    PERMISSION: "permission",
    PRODUCT: "product",
    CUSTOMER: "customer",
    WAREHOUSE: "warehouse",
    DO: "delivery_order",
    ARMADA: "armada",
    PENGIRIMAN: "shipment",
    LAPORAN: "report",
  },
};
