export const SHIPMENT_TYPE = {
  ANTAR: "ANTAR",
  JEMPUT: "JEMPUT",
};

export const LOCATION_TYPE = {
  RUMAH: "RUMAH",
  KANTOR: "KANTOR",
  GUDANG: "GUDANG",
  TOKO: "TOKO",
  PABRIK: "PABRIK",
  LAINNYA: "LAINNYA",
};

export const SHIPMENT_STATUS = {
  PENDING: "PENDING",
  PROSES: "PROSES",
  COMPLETED: "COMPLETED",
  SELESAI: "SELESAI",
  CANCEL: "CANCEL",
};

export const SHIPMENT_TYPE_LABELS = {
  [SHIPMENT_TYPE.ANTAR]: "Antar",
  [SHIPMENT_TYPE.JEMPUT]: "Jemput",
};

export const SHIPMENT_STATUS_LABELS = {
  [SHIPMENT_STATUS.PENDING]: "Pending",
  [SHIPMENT_STATUS.PROSES]: "Proses",
  [SHIPMENT_STATUS.COMPLETED]: "Completed",
  [SHIPMENT_STATUS.SELESAI]: "Completed",
  [SHIPMENT_STATUS.CANCEL]: "Cancel",
};
